# Generated by Django 2.2 on 2019-10-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_tamanho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanho',
            old_name='altura',
            new_name='nome',
        ),
    ]
