# Generated by Django 2.2 on 2019-10-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='precos', to='produto.Preco'),
            preserve_default=False,
        ),
    ]
