# Generated by Django 2.2 on 2019-11-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_preco_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_id',
        ),
    ]
