# Generated by Django 2.2 on 2019-11-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20191118_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
