# Generated by Django 2.2 on 2019-12-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
