# Generated by Django 2.2 on 2020-01-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='preco',
            field=models.IntegerField(max_length=10),
        ),
    ]
