# Generated by Django 2.2 on 2020-01-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20200101_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(max_length=10),
        ),
    ]
