# Generated by Django 2.2 on 2020-01-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_auto_20200101_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
